# Add your Supabase credentials here for local development
supabase_url = "https://pyeunyfneqrqbrnsmphv.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5ZXVueWZuZXFycWJybnNtcGh2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDczODg0NiwiZXhwIjoyMDYwMzE0ODQ2fQ.xz9DVlYXBuCZbQsVFCXt1tS_azhZ-CMic2d7oDHirS0"
